In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

from src.process import load_data, clean_data, aggregate_monthly
from src.model import add_lags, train_and_predict
from src.utils import print_section

In [2]:
print_section("Load and clean raw data")

df = load_data("data/rawdata.csv")
df = clean_data(df)

df.head()

============================================================
Load and clean raw data
============================================================

       STATION       DATE  PRCP  TMAX  TMIN
0  USW00012839 1996-06-07  0.15  89.0  77.0
1  USW00012839 1996-06-08  0.00  91.0  77.0
2  USW00012839 1996-06-09  0.45  92.0  73.0
3  USW00012839 1996-06-10  1.35  88.0  72.0
4  USW00012839 1996-06-11  0.42  88.0  76.0

In [3]:
print_section("Aggregate daily to monthly")

monthly = aggregate_monthly(df)

# Save monthly dataset for reference
monthly.to_csv("data/monthly_data.csv", index=False)

monthly.head()

============================================================
Aggregate daily to monthly
============================================================

,STATION,year,month,PRCP_sum,TMAX_mean,TMIN_mean,TMEAN,ym
0,USW00003017,1996,6,1.74,85.083333,53.291667,69.187500,1996-06-01
1,USW00003017,1996,7,1.01,87.967742,58.774194,73.370968,1996-07-01
2,USW00003017,1996,8,0.56,87.064516,56.129032,71.596774,1996-08-01
3,USW00003017,1996,9,2.34,74.600000,46.900000,60.750000,1996-09-01
4,USW00003017,1996,10,0.39,64.903226,36.774194,50.838710,1996-10-01

In [4]:
print_section("Add lag features")

monthly_lag = add_lags(monthly)
monthly_lag.head()

============================================================
Add lag features
============================================================

,STATION,year,month,PRCP_sum,TMAX_mean,TMIN_mean,TMEAN,ym,lag1_TMEAN,lag1_PRCP
0,USW00003017,1996,6,1.74,85.083333,53.291667,69.187500,1996-06-01,NaN,NaN
1,USW00003017,1996,7,1.01,87.967742,58.774194,73.370968,1996-07-01,69.187500,1.74
2,USW00003017,1996,8,0.56,87.064516,56.129032,71.596774,1996-08-01,73.370968,1.01
3,USW00003017,1996,9,2.34,74.600000,46.900000,60.750000,1996-09-01,71.596774,0.56
4,USW00003017,1996,10,0.39,64.903226,36.774194,50.838710,1996-10-01,60.750000,2.34

In [14]:
print_section("Train models and generate predictions")

============================================================
Train models and generate predictions
============================================================